# Generated by Django 6.0.4 on 2026-04-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('longitudinal_crack', 'Longitudinal Crack'), ('transverse_crack', 'Transverse Crack'), ('alligator_crack', 'Alligator Crack'), ('pothole', 'Pothole'), ('patch_repair_area', 'Patch/Repair Area'), ('other_surface_damage', 'Other Surface Damage'), ('manhole_road_utility_cover', 'Manhole/Road Utility Cover')], max_length=50)),
                ('severity', models.FloatField()),
                ('confidence', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmph', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField()),
                ('image_crop_path', models.CharField(max_length=500)),
                ('full_frame_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
