# Generated by Django 6.0.4 on 2026-04-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frame',
            field=models.ImageField(blank=True, null=True, upload_to='frames/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_crop',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.device'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('longitudinal_crack', 'Longitudinal Crack'), ('transverse_crack', 'Transverse Crack'), ('alligator_crack', 'Alligator Crack'), ('pothole', 'Pothole'), ('patch_repair_area', 'Patch/Repair Area'), ('other_surface_damage', 'Other Surface Damage'), ('manhole_road_utility_cover', 'Manhole/Road Utility Cover'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_crop_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='severity',
            field=models.FloatField(default=0.0),
        ),
    ]
