# Generated by Django 6.0.4 on 2026-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('pothole', 'Pothole'), ('longitudinal_crack', 'Longitudinal Crack'), ('transverse_crack', 'Transverse Crack'), ('alligator_crack', 'Alligator Crack'), ('patch_repair', 'Patch Repair'), ('other_surface_damage', 'Other Surface Damage')], default='other_surface_damage', max_length=50),
        ),
    ]
